# image:
#   name: atlassian/pipelines-awscli


pipelines:
  branches:
    master:
      - step: 
          name: Test the pipelines
          deployment: prod_build
          image: atlassian/default-image:2
          script:
            - echo all the varrrrssss...
            - export ALL_THE_VARS=$(declare -x -F)
            - echo "$ALL_THE_VARS"
            - echo $PATAPI_DB_HOST
            - echo "The port is...$PATAPI_PORT !!!!"
            - echo "My region is $AWS_DEFAULT_REGION"
            - echo "$PATAPI_API_KEY"
            - echo $PATAPI_API_KEY
            - echo "my api key is...$PATAPI_API_KEY"
            - echo $PATAPI_API_KEY | base64 -di > ./patapi_api_key
            - cat ./patapi_api_key
      - step:
          name: Get k8s Credentials
          deployment: prod_k8s-creds
          image: atlassian/default-image:2
          script:
            - mkdir kube
            - echo $KUBE_TOKEN | base64 -d > ./kube/kube_token
            - echo $KUBE_CA | base64 -d > ./kube/kube_ca
          artifacts:
            - kube/*
      - step:
          name: Try k8s things
          image: atlassian/pipelines-kubectl
          deployment: prod_deploy
          script:
            - echo trying k8s...
            - echo "My region is $AWS_DEFAULT_REGION"
            - export BUILD_ID="$BITBUCKET_BRANCH"_"$BITBUCKET_COMMIT"_"$BITBUCKET_BUILD_NUMBER"
            - export IMAGE_NAME="$AWS_REGISTRY_URL":"$BUILD_ID"
            - echo "kubectl time..."
            - kubectl config set-cluster pat-api-k8s --server=https://fcae1d7e-5f25-4d97-b187-b81f25326a71.k8s.ondigitalocean.com --certificate-authority="$(pwd)/kube/kube_ca"
            - kubectl config set-credentials bitbucket --token="$(cat ./kube/kube_token)"
            - kubectl config set-context development --cluster=pat-api-k8s --user=bitbucket
            - kubectl config use-context development
            - echo More k8s info...
            - export CLUSTER_INFO=$(kubectl cluster-info)
            - export KUBE_ALL=$(kubectl get all)
            - echo $CLUSTER_INFO
            - echo $KUBE_ALL


