# image:
#   name: atlassian/pipelines-awscli

pipelines:
  branches:
    master:
      - step: 
          name: Test the pipelines
          script:
            - echo all the varrrrssss...
            - declare -x -F | echo
      - step:
          name: Try k8s things
          script:
            - echo trying k8s...
            - export BUILD_ID="$BITBUCKET_BRANCH"_"$BITBUCKET_COMMIT"_"$BITBUCKET_BUILD_NUMBER"
            - export IMAGE_NAME="$AWS_REGISTRY_URL":"$BUILD_ID"
            - echo Getting kubectl...
            - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/- kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            - chmod +x ./kubectl
            - sudo mv ./kubectl /usr/local/bin/kubectl
            - echo Make token files...
            - echo $KUBE_TOKEN | base64 --decode > ./kube_token
            - echo $KUBE_CA | base64 --decode > ./kube_ca
            - echo "kubectl time..."
            - kubectl config set-cluster pat-api-k8s --server=https://fcae1d7e-5f25-4d97-b187-b81f25326a71.k8s.ondigitalocean.com --certificate-authority="$(pwd)/kube_ca"
            - kubectl config set-credentials bitbucket --token="$(cat ./kube_token)"
            - kubectl config set-context development --cluster=pat-api-k8s --user=bitbucket
            - kubectl config use-context development
            - echo More k8s info...
            - kubectl cluster-info | echo
            - kubectl get all | echo


