version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    volumes:
      - ./:/app
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres
    expose:
      - 5432
    ports:
      - 5433:5432
    volumes:
      - /Users/patjacobs/docker/volumes/postgres
    environment:
      POSTGRES_DB: pat_api
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: 5NMMqWwQcipc1iCiQ8Dqh
      