FROM node:16.13.1

WORKDIR /app

COPY ./package.json .
COPY ./tsconfig.json .
COPY yarn.lock .
RUN npm install -g nodemon ts-node typescript && yarn

COPY ./ .

EXPOSE 4000

CMD ["yarn", "start:nodemon"]
