version: "3"

services:
  app:
    context: .
    volumes:
      - ./:/app
    depends_on:
      - mongo

  mongo:
    image: pat-api-mongo
    expose:
      -27017
    volumes:
      - ./data/db:/data/db